const ACTION_TYPE_TOGGLE_WORD = 'TOGGLE_WORD';
const ACTION_TYPE_REMOVE_WORD = 'REMOVE_WORD';
const ACTION_TYPE_SET_FILTER_MODE = 'SET_FILTER_MODE';
const ACTION_TYPE_ADD_WORD = 'ADD_WORD';

export default {
  ACTION_TYPE_TOGGLE_WORD,
  ACTION_TYPE_REMOVE_WORD,
  ACTION_TYPE_SET_FILTER_MODE,
  ACTION_TYPE_ADD_WORD,
};
